// Code generated by "stringer -type=TokenType"; DO NOT EDIT

package sexp

import "fmt"

const (
	_TokenType_name_0 = "LEFTRIGHT"
	_TokenType_name_1 = "RAW_STRING"
	_TokenType_name_2 = "NUMBER"
	_TokenType_name_3 = "QUOTE_STRING"
	_TokenType_name_4 = "EOF"
	_TokenType_name_5 = "INVALID"
)

var (
	_TokenType_index_0 = [...]uint8{0, 4, 9}
	_TokenType_index_1 = [...]uint8{0, 10}
	_TokenType_index_2 = [...]uint8{0, 6}
	_TokenType_index_3 = [...]uint8{0, 12}
	_TokenType_index_4 = [...]uint8{0, 3}
	_TokenType_index_5 = [...]uint8{0, 7}
)

func (i TokenType) String() string {
	switch {
	case 40 <= i && i <= 41:
		i -= 40
		return _TokenType_name_0[_TokenType_index_0[i]:_TokenType_index_0[i+1]]
	case i == 66:
		return _TokenType_name_1
	case i == 78:
		return _TokenType_name_2
	case i == 81:
		return _TokenType_name_3
	case i == 9220:
		return _TokenType_name_4
	case i == 65533:
		return _TokenType_name_5
	default:
		return fmt.Sprintf("TokenType(%d)", i)
	}
}
